[project]
name = "rag"
version = "0.1.0"
description = RAG Project""
readme = "README.md"
authors = [
    { name = "Omer Aytug", email = "aytugomer00@gmail.com" }
]
requires-python = ">=3.13"
dependencies = ["backend", "frontend"]

[tool.uv.sources]
backend = { workspace = true }
frontend = { workspace = true }

[tool.uv.workspace]
members = ["src/rag/frontend", "src/rag/backend"]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
